from sqlalchemy import Column, Integer, String, Float, Text
from datetime import datetime, timezone
from ..database import Base


class ExpiryDefault(Base):
    __tablename__ = "expiry_defaults"

    id = Column(Integer, primary_key=True, index=True)
    category = Column(String, nullable=False, index=True)
    name_pattern = Column(String, nullable=False)
    storage_type = Column(String, nullable=False)
    default_days = Column(Integer, nullable=False)
    notes = Column(String, nullable=True)
    priority = Column(Integer, default=0)  # higher = checked first


class SatelliteDevice(Base):
    """A pi_remote device known to this main server.

    Rows are created/refreshed when a satellite pulls its config (the heartbeat
    rides along on that existing request), and may also be seeded by a manual
    LAN scan. The server uses the table to list remotes with their address,
    version and last-seen time, and to queue a command for a device to pick up
    on its next heartbeat (topology independent: the device always dials out)."""
    __tablename__ = "satellite_devices"

    id = Column(Integer, primary_key=True, index=True)
    device_id = Column(String, nullable=False, unique=True, index=True)
    hostname = Column(String, nullable=True)
    ip = Column(String, nullable=True)
    deployment_mode = Column(String, nullable=True)
    version = Column(String, nullable=True)
    label = Column(String, nullable=True)          # admin-assigned friendly name
    source = Column(String, default="heartbeat")   # heartbeat | scan
    pending_command = Column(String, nullable=True)  # queued command name, drained on heartbeat
    first_seen = Column(
        String, default=lambda: datetime.now(timezone.utc).isoformat(timespec="seconds")
    )
    last_seen = Column(
        String, default=lambda: datetime.now(timezone.utc).isoformat(timespec="seconds")
    )


class StreamDeckProfile(Base):
    """A named Stream Deck key layout saved by the user.

    Profiles are stored on the main server and mirrored to satellites via the
    satellite config sync. Each profile targets a specific deck size (6, 15, or
    32 keys) so a device can filter to profiles that match its hardware.
    key_overrides is a JSON array of per-slot override dicts (same format as
    settings.streamdeck_key_overrides)."""
    __tablename__ = "streamdeck_profiles"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False, unique=True, index=True)
    deck_size = Column(Integer, nullable=False)  # 6, 15, or 32
    key_overrides = Column(Text, default="[]")   # JSON array
    created_at = Column(
        String, default=lambda: datetime.now(timezone.utc).isoformat(timespec="seconds")
    )
    updated_at = Column(
        String, default=lambda: datetime.now(timezone.utc).isoformat(timespec="seconds")
    )


class PendingItem(Base):
    """Item scanned by a headless scanner, awaiting review/commit to Grocy."""
    __tablename__ = "pending_items"

    id = Column(Integer, primary_key=True, index=True)
    barcode = Column(String, nullable=True, index=True)
    name = Column(String, nullable=False)
    quantity = Column(Float, default=1.0)
    unit = Column(String, default="item")
    category = Column(String, default="Other")
    storage_type = Column(String, default="refrigerated")
    best_by_date = Column(String, nullable=True)   # ISO date string
    brand = Column(String, nullable=True)
    notes = Column(String, nullable=True)
    lookup_failed = Column(Integer, default=0)     # 1 = OFF lookup failed, needs manual name
    source = Column(String, default="scanner")     # scanner | ha | esp32 | manual
    created_at = Column(
        String, default=lambda: datetime.now(timezone.utc).isoformat(timespec="seconds")
    )


class ActionItem(Base):
    """A persistent notification / action item shown in the Action Items inbox
    (FoodAssistant-iut3). Generated by the app (expired food, a leftovers prompt)
    and resolved by the user with quick actions (archive, snooze, resolve)."""
    __tablename__ = "action_items"

    id = Column(Integer, primary_key=True, index=True)
    kind = Column(String, nullable=False, index=True)   # food_expired | leftover_prompt | generic
    title = Column(String, nullable=False)
    body = Column(String, nullable=True)
    # open | snoozed | archived | done. Indexed so the inbox query stays cheap.
    status = Column(String, nullable=False, default="open", index=True)
    snooze_until = Column(String, nullable=True)         # ISO datetime while snoozed
    # Stable key so a regenerated item (e.g. the same expired product) updates the
    # existing row instead of piling up duplicates. Unique per logical item.
    dedupe_key = Column(String, nullable=True, index=True)
    level = Column(String, default="info")               # info | success | warning | error
    payload = Column(Text, nullable=True)                # JSON: action context
    created_at = Column(
        String, default=lambda: datetime.now(timezone.utc).isoformat(timespec="seconds")
    )
    updated_at = Column(
        String, default=lambda: datetime.now(timezone.utc).isoformat(timespec="seconds")
    )


class RecipeCookCount(Base):
    """How many times a recipe has been cooked (FoodAssistant-bjps).

    One row per recipe identity: a stable key derived from the recipe's source
    plus its upstream id (Mealie slug, TheMealDB/Spoonacular/Forager external
    id), or a normalized title when no id is available. Any cook path (the
    Recipes page Cook button, the Current Recipe "Mark cooked", a course cook)
    bumps ``count`` and refreshes ``last_cooked_at``, so the browse cards can
    show a "Made N times" note. Purely additive: never read on a hot path
    without a batch lookup, and every write and read fails soft so a cook is
    never blocked by a bookkeeping error."""
    __tablename__ = "recipe_cook_counts"

    id = Column(Integer, primary_key=True, index=True)
    # Stable identity from services/cook_counts.cook_identity. Unique so a repeat
    # cook of the same recipe updates its row instead of adding another.
    recipe_key = Column(String, nullable=False, unique=True, index=True)
    title = Column(String, nullable=True)   # last-seen title, for readability only
    source = Column(String, nullable=True)  # mealie | themealdb | spoonacular | forager
    count = Column(Integer, default=0)
    last_cooked_at = Column(String, nullable=True)  # ISO datetime of the last cook


class IntakeLog(Base):
    """One logged food/meal in the food-intake tracker (FoodAssistant-e6qt).

    Records what was eaten and its nutrition so the Nutrition page can show
    daily totals. Macros are per the logged servings (already multiplied), so a
    day's total is a straight sum. ``date`` is the local calendar day
    (YYYY-MM-DD) the entry counts toward, kept denormalised so the day query is
    a simple index lookup."""
    __tablename__ = "intake_log"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    servings = Column(Float, default=1.0)
    calories = Column(Float, nullable=True)
    protein = Column(Float, nullable=True)   # grams
    carbs = Column(Float, nullable=True)     # grams
    fat = Column(Float, nullable=True)       # grams
    date = Column(String, nullable=False, index=True)   # local YYYY-MM-DD
    source = Column(String, default="manual")  # manual | barcode | recipe
    created_at = Column(
        String, default=lambda: datetime.now(timezone.utc).isoformat(timespec="seconds")
    )
